-- Drop table

-- DROP TABLE IF EXISTS public.voter;

CREATE TABLE IF NOT EXISTS public.voter (
	county_code varchar(3) NOT NULL,
	id varchar(10) NOT NULL,
	name_last varchar(30) NOT NULL,
	name_suffix varchar(5) NOT NULL,
	name_first varchar(30) NOT NULL,
	name_middle varchar(30) NOT NULL,
	exemption varchar(1) NOT NULL,
	residential_address_line_1 varchar(50) NOT NULL,
	residential_address_line_2 varchar(40) NOT NULL,
	residential_city varchar(40) NOT NULL,
	residential_state varchar(2) NOT NULL,
	residential_zipcode varchar(10) NOT NULL,
	mailing_address_line_1 varchar(40) NOT NULL,
	mailing_address_line_2 varchar(40) NOT NULL,
	mailing_address_line_3 varchar(40) NOT NULL,
	mailing_city varchar(40) NOT NULL,
	mailing_state varchar(2) NOT NULL,
	mailing_zipcode varchar(12) NOT NULL,
	mailing_country varchar(40) NOT NULL,
	gender varchar(1) NOT NULL,
	race varchar(1) NOT NULL,
	birth_date date NULL,
	registration_date date NULL,
	party_affiliation varchar(3) NOT NULL,
	precinct varchar(6) NOT NULL,
	precinct_group varchar(3) NOT NULL,
	precinct_split varchar(6) NOT NULL,
	precinct_suffix varchar(3) NOT NULL,
	voter_status varchar(3) NOT NULL,
	congressional_district varchar(3) NOT NULL,
	house_district varchar(3) NOT NULL,
	senate_district varchar(3) NOT NULL,
	county_commission_district varchar(3) NOT NULL,
	school_board_district varchar(2) NOT NULL,
	daytime_areacode varchar(3) NOT NULL,
	daytime_phone varchar(7) NOT NULL,
	daytime_phone_extension varchar(4) NOT NULL,
	email varchar(100) NOT NULL,
	export_date date NULL,
	CONSTRAINT voter_pk PRIMARY KEY (id, export_date)
);
