---
steps:
  - checkout: self
  - script: echo Hello, world!
    displayName: 'Run a one-line script'
  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
  - task: Docker@2
    inputs:
      containerRegistry: 'gl_registry'
      command: 'login'
    displayName: Login to registry
  - task: Docker@2
    displayName: Build Container
    inputs:
      containerRegistry: 'gl_registry'
      repository: $(containerPath)/$(Build.Repository.Name)
      arguments: --network=host --build-arg DIGITALOCEAN_ACCESS_TOKEN=$(DIGITALOCEAN_ACCESS_TOKEN)
      command: 'build'
      tags: |
        latest
  - task: Docker@2
    displayName: Push Container
    inputs:
      containerRegistry: 'gl_registry'
      repository: $(containerPath)/$(Build.Repository.Name)
      command: push
      tags: |
        latest
